<?
$html_root="{html_root}";
$domain_title="{domain_title}";
$titleTagline="{titleTagline}";
$adminName="{adminName}";
$adminEmail="{adminEmail}";
$adminPassword="{adminPassword}";
$twitterHandle="{twitterHandle}";
$dbHost="{dbHost}";
$dbDatabase="{dbDatabase}";
$dbUsername="{dbUsername}";
$dbPassword="{dbPassword}";
$imageDirectory="{imageDirectory}";
$searchDescription="{searchDescription}";
$socialMediaThumbIMG="{socialMediaThumbIMG}";
$searchKeywords="{searchKeywords}";
$googleAnalytics="{googleAnalytics}";
?>