<?
$html_root="";
$domain_title="";
$titleTagline="";
$adminName="";
$adminEmail="";
$adminPassword="";
$twitterHandle="";
$dbHost="";
$dbDatabase="";
$dbUsername="";
$dbPassword="";
$imageDirectory="";
$searchDescription="";
$socialMediaThumbIMG="";
$searchKeywords="";
$googleAnalytics="";
?>